version: '3.9'

services:
  mongodb:
    image: 'mongo:latest'
    restart: always
    ports:
      - '27017:27017'
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
